In [2]:
import numpy as np

In [2]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [4]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [5]:
np.zeros((3,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [6]:
#If we need equally spaced integers
np.linspace(0,11,10)

array([ 0.        ,  1.22222222,  2.44444444,  3.66666667,  4.88888889,
        6.11111111,  7.33333333,  8.55555556,  9.77777778, 11.        ])

In [3]:
np.arange(1,21,2)

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19])

In [26]:
np.random.randint(1,10)

6

In [48]:
np.random.seed(101)
np.random.randint(1,100,(3,3))

array([[96, 12, 82],
       [71, 64, 88],
       [76, 10, 78]])

In [49]:
np.random.seed(101)
arr=np.random.randint(1,100,10)

In [50]:
arr

array([96, 12, 82, 71, 64, 88, 76, 10, 78, 41])

In [51]:
arr.max()

96

In [52]:
arr.min()

10

In [54]:
arr.reshape(2,5)

array([[96, 12, 82, 71, 64],
       [88, 76, 10, 78, 41]])

In [63]:
mat=np.arange(0,100).reshape(10,10)

In [61]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [9]:
np.random.randn(3)

array([-0.29472469,  1.27711461, -1.56362526])

In [10]:
np.random.rand(5)

array([0.36576313, 0.22758887, 0.77548681, 0.65300838, 0.12632252])

In [11]:
np.random.rand(5,5)

array([[0.60465727, 0.93833512, 0.28293235, 0.96357211, 0.78187607],
       [0.67228428, 0.14882513, 0.37699611, 0.14216846, 0.78149033],
       [0.44967864, 0.61824101, 0.40063853, 0.82250797, 0.28541979],
       [0.67772913, 0.19149616, 0.72349256, 0.98014722, 0.29140571],
       [0.11976079, 0.10065565, 0.28077408, 0.18259331, 0.77437692]])

In [4]:
arr=np.random.randint(0,25,25)

In [17]:
arr.reshape(5,5)

array([[24, 23, 23,  2, 22],
       [ 6,  9, 10, 17, 13],
       [ 9,  4,  9, 18, 20],
       [ 7, 16, 20,  6, 17],
       [11, 20,  7, 24,  5]])

In [18]:
arr.max()

24

In [19]:
arr.min()

2

In [20]:
arr.argmax()

0

In [21]:
arr.argmin()

3

In [26]:
from numpy.random import randint
randint(1,10)

7

In [5]:
arr.dtype

dtype('int32')

In [6]:
arr=np.arange(0,11)

In [7]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [8]:
arr_cpy = arr.copy()

In [9]:
arr_cpy

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [10]:
arr_cpy[:]=100

In [11]:
arr_cpy

array([100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100])

In [12]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [14]:
bool_arr = arr>5

In [15]:
bool_arr

array([False, False, False, False, False, False,  True,  True,  True,
        True,  True])

In [16]:
arr[bool_arr] #Prints the only contents where conditions are true

array([ 6,  7,  8,  9, 10])

In [17]:
arr[arr>5]

array([ 6,  7,  8,  9, 10])

In [18]:
arr/arr

C:\Users\MegaTron\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in true_divide
  """Entry point for launching an IPython kernel.


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])